#!/usr/bin/env python3

# Simple scripts for helping manage my rom

import sys
import os

exit = sys.exit
#os.system = lambda x: print(x)

cwd = os.getcwd()

manifest_link = 'git://github.com/Bianca-Project/android.git'
manifest_branch = 'q'

path_link = 'https://github.com/LineageOS/'
path_branch ='lineage-17.1'
path_folder = [
  'packages/apps/Settings',
  'vendor/lineage',
  'frameworks/base'
  ]
path_repo = [
  'android_packages_apps_Settings',
  'android_vendor_lineage',
  'android_frameworks_base'
  ]

def resync_all():
  ret = os.system('repo init -u %s -b %s'%(manifest_link, manifest_branch))
  # if ret is not None: exit(1)
  os.system('repo sync -c --force-sync --no-tags --no-clone-bundle --optimized-fetch --prune')

def merge(val):
  x = 0
  for i in path_folder:
    if val in i:
      folder = path_folder[x]
      repo = path_repo[x]
    x += 1

  os.chdir(cwd + '/' + folder)
  os.system('echo $(pwd)')

  ret = os.system('git fetch {} {}'.format(path_link + repo, path_branch))
  # if ret is not None: exit(1)
  ret = os.system('git merge FETCH HEAD')
  # if ret is not None: exit(1)

  os.chdir(cwd)

def push(val):
  x = 0
  for i in path_folder:
    if val in i:
      folder = path_folder[x]
      repo = path_repo[x]
    x += 1

  os.chdir(cwd + '/' + folder)
  os.system('echo $(pwd)')

  ret = os.system('git push {} {}'.format('https://github.com/Bianca-Project/' + repo, manifest_branch))
  # if ret is not None: exit(1)

  os.chdir(cwd)

def show_help():
  print('\tBianca Project')
  print('Simple scripts for manage my rom\n')
  print('Usage: resync [command] [argument]\n')
  print('Commands:')
  print('all\t\tResync all repo')
  print('merge\t\tMerge repo from source')
  print('push\t\tPush repo to github')
  print('help\t\tShow this help')

if __name__ == "__main__":
  args = sys.argv

  if len(args) == 1:
    show_help()
    exit(1)

  elif args[1] == 'help':
    show_help()

  elif args[1] == 'all':
    resync_all()

  elif args[1] == 'merge':
    if len(args) == 2:
      print('Need more argument!')
      exit(1)
    merge(args[2:][0])

  elif args[1] == 'push':
    if len(args) == 2:
      print('Need more argument!')
      exit(1)
    push(args[2:][0])

  else:
    print('Unknown command!!')
    print('Check with command help')
    exit(1)
